### ISSUE TITLE
FAQ? 

### ISSUE THREAD

**Issue by Adam-Meisen** [kahkhang/kube-linode#24]
This project looks neat and I'd like to try it out, but I have a few questions before I give it an API key. I figured it might be useful to start an issue for questions like this.

Can this be run on an existing server, or will start its own?

Does this require multiple servers? The .gif example shows two.

Is there a minimum size recommendation for the server? Will this work on a single $5 linode, or does it require  more resources? 

What actions can this program perform on my Linode account? It's probably a good idea to have this in the docs, if the program can do anything to an account that would incur fees. 

Edit: Sorry, I wrote this on mobile and hit "submit" before I meant to.

**Comment by kahkhang** [comment]
Hi @Adam-Meisen, thanks for posting these questions which I have left out!

1) This script will start new CoreOS linode instances. Depending on your current server OS distribution, I would recommend looking at Bootkube (for CoreOS) or Juju (for Ubuntu) if you want to provision a kubernetes cluster in Ubuntu.

2) This does not require multiple servers. You can simply provision a kubernetes master node and schedule your pods in it. One caveat is that rook file storage will not be installed (since it is a distributed storage system hence it doesn't really make sense to run on one node), so you should use hostpath volumes if you only have one master node. Also, your pods would need to have the following tolerations to schedule on the master node

```
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
```

4) The minimum size recommendation is the $10/mo instance for the master node, and any size instance for the worker nodes. You can try a $5/mo instance for the master node, but I would suggest you forego kubernetes if you do that since the kubernetes memory/cpu overhead would be significant compared to just running your applications

5) It spins linode instances according to the plans and the number of instances that you specified. Note that linode charges per hour so if you use the script to spin up a $10/mo node, you are incurring $0.015/hour (see https://www.linode.com/pricing)

**Comment by Adam-Meisen** [comment]
Thanks, that saved me a lot of trouble.
