### ISSUE TITLE
Customization options

### ISSUE THREAD

**Issue by devdlabs** [kahkhang/kube-linode#48]
Hi @kahkhang thanks for this repo. It worked flawlessly :+1:  I would like to know tips for changing coreos version and customize others stacks

**Comment by kahkhang** [comment]
HI @devdlabs , hmm upgrading involves changing the kubernetes manifests, as well as the systemd config for kubelet.service. As for other stacks, if you are looking at installing other applications, I would recommend starting with Kubernetes Helm (https://github.com/kubernetes/charts) since it is rather easy to install. I might create a tutorial sometime on how to update the manifests file in the future, so stay tuned!
